#!/usr/bin/env node
/**
 * Import map from Excel "🗺 База" sheet into web/world_base.js
 * Usage: node tools/import-map.js [path/to/Sheets & Sorcery.xlsx]
 * Default: ./Sheets & Sorcery.xlsx (from project root)
 */

const fs = require("node:fs");
const path = require("node:path");

const SHEET_NAME = "🗺 База";
const GRID_W = 26;
const GRID_H = 32;
const OUTPUT = path.join(__dirname, "../web/world_base.js");

let XLSX;
try {
	XLSX = require("xlsx");
} catch (e) {
	console.error("Install xlsx: npm install xlsx");
	process.exit(1);
}

const xlsxPath = process.argv[2] || path.join(__dirname, "../Sheets & Sorcery.xlsx");

if (!fs.existsSync(xlsxPath)) {
	console.warn(`File not found: ${xlsxPath}`);
	console.warn("Using placeholder. Place the Excel file and re-run to import.");
	process.exit(0);
}

const wb = XLSX.readFile(xlsxPath);
let sh = wb.Sheets[SHEET_NAME];

if (!sh) {
	const names = Object.keys(wb.Sheets);
	sh = wb.Sheets[names.find((n) => n.includes("База")) || names[0]];
}

if (!sh) {
	console.error("No sheet found");
	process.exit(1);
}

// Apps Script grid: C3:AB34 = col C(2) to AB(27), row 3 to 34
const START_COL = 2; // C
const START_ROW = 2; // row 3 (0-indexed)
const range = XLSX.utils.decode_range(sh["!ref"] || "A1");
const data = [];
for (let R = START_ROW; R < START_ROW + GRID_H; R++) {
	const row = [];
	for (let C = START_COL; C < START_COL + GRID_W; C++) {
		const addr = XLSX.utils.encode_cell({ r: R, c: C });
		const cell = sh[addr];
		const val = cell ? String(cell.v || "").trim() : "";
		row.push(val || "⬜️");
	}
	while (row.length < GRID_W) row.push("⬜️");
	data.push(row);
}

while (data.length < GRID_H) {
	data.push(Array(GRID_W).fill("⬜️"));
}

const rows = data.map((r) => `  [${r.map((c) => JSON.stringify(c)).join(", ")}]`).join(",\n");

const out = `// ===== Sheets & Sorcery: World Base Map =====
// 26×32 grid — generated by tools/import-map.js from Excel "🗺 База"

import { GRID_W, GRID_H } from "./config.js";

const PLACEHOLDER = [
${rows}
];

function ensureDimensions(grid) {
  const out = [];
  for (let y = 0; y < GRID_H; y++) {
    const row = [];
    for (let x = 0; x < GRID_W; x++) {
      const val = (grid[y] && grid[y][x]) ? String(grid[y][x]).trim() : "⬜️";
      row.push(val || "⬜️");
    }
    out.push(row);
  }
  return out;
}

export const WORLD = ensureDimensions(PLACEHOLDER);
`;

fs.writeFileSync(OUTPUT, out, "utf8");
console.log(`Wrote ${OUTPUT} (${GRID_W}×${GRID_H})`);
process.exit(0);
